### ISSUE TITLE
No main function for fast api file 

### ISSUE THREAD

**Issue by saakethch** [sidhujag/autogen-backend#1]
Hey, This code is really well written !very beneficial ,
Could you please tell how to run the code ? I have  tried py main.py and docker build foldername/ .

**Comment by sidhujag** [comment]
yes sure will update the readme.. it goes with the autogen fork https://github.com/sidhujag/autogen

**Comment by sidhujag** [comment]
Overall to get you going: 
backend:
`
python3 -m venv venv && source venv/bin/activate && pip install --upgrade -r requirements.txt &&
uvicorn main:app --reload --host localhost --port 8001
`

for client (autogen):
`
pip install .
uvicorn main:app --reload --host localhost
`
